name: 'portfolio_2025'
version: '1.0.0'
config-version: 2

profile: 'portfolio_2025'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  p02_snowflake_dbt:
    +materialized: view
    staging:
      +schema: staging
    core:
      +schema: core
    marts:
      +schema: marts
